# python main.py recognition -c config/ntu120_xsub/test.yaml
work_dir: ./work_dir/ntu60/xsub/paring_test

# feeder
feeder: feeders.feeder_parsing.Feeder
test_feeder_args:
  debug: False
  random_interval: False
  temporal_rgb_frames: 5
  sample_path: data/ntu/xsub/CTR_NTU60_Xview_valsample.txt
  label_path: data/ntu/xsub/CTR_NTU60_Xview_vallabel.txt

# model
model: net.inceptionV3.Model
model_args:
  num_class: 120

# test
phase: test
device: [0,1,2,3]

# debug
debug: False
